apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-elasticsearch
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s-elasticsearch
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s-elasticsearch
    spec:
      containers:
        - name: spring-boot-k8s-elasticsearch
          image: springboot-k8s-elasticsearch:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
